name: Create Release

on: 
  workflow_dispatch:
                  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Repository Checkout
          uses: actions/checkout@v2

        - name: Setup NodeJs
          uses: actions/setup-node@v1
          with:
              node-version: '14'

        - name: Install Dependencies
          run: npm install

        - name: Create Release
          run: npm run release

        - name: Get Version for Tag
          id: package-version
          uses: martinbeentjes/npm-get-version-action@master

        - name: Commit, Tag and Push Changes
          uses: EndBug/add-and-commit@v4
          with:
            message: "New release created"
            add: "-A"
            tag: "v${{ steps.package-version.outputs.current-version}}"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
